### PR TITLE
fix(idea/frontend): hide message name on error

### LINKED ISSUE #1693: Incorrect display of 'service' and 'function' for reply message with panic
### Problem

'Service' and 'function' is displayed incorrectly when the reply message contains panic
8B7PgbVoAO

### Steps

1. Go to https://staging-env.gear-tech.io/send/message/0x712c8bbc984ad82b3db9a287ba81034598ba502babb490359b9f811c07ba5bf2?node=wss%3A%2F%2Ftestnet.vara-network.io
2. Select Service - Ticatactoe
3. Select function - StartGame
4. Calculate gas and send message
5. Wait 1 minute for your turn to end
6. Select function - Turn
7. Fill in '1' in the step (U8) field
8. Calculate gas and send message
9. Go to https://staging-env.gear-tech.io/programs/0x712c8bbc984ad82b3db9a287ba81034598ba502babb490359b9f811c07ba5bf2?node=wss%3A%2F%2Ftestnet.vara-network.io
10. Click 'Messages' ➝ 'From program'
11. Open message with an error 

### Possible Solution

_No response_

### Notes

_No response_

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
```

</p>
</details>

### PR DESCRIPTION
**Pull request by vraja-nayaka**
Resolves #1693

### CODE REVIEW

File: idea/frontend/src/features/message/ui/message-card/message-card.tsx [hunk 1]
```diff
@@ -19,7 +19,8 @@ type Props = {
 const MessageCard = ({ isToDirection, message }: Props) => {
   const { id, timestamp, service, fn } = message;
 
-  const hasName = Boolean(service || fn);
+  const hideServiceAndFn = 'exitCode' in message && message.exitCode !== 0;
```
Comment (nikitayutanov) [inline idea/frontend/src/features/message/ui/message-card/message-card.tsx:22]: Wouldn't be better to use `isMessageWithError` util?

File: idea/frontend/src/pages/message/message.tsx [hunk 2]
```diff
@@ -35,6 +35,7 @@ const Message = () => {
   const message = messageToProgram.data || messageFromProgram.data;
   const isLoading = messageToProgram.isLoading || messageFromProgram.isLoading;
   const { timestamp, id, source, value, destination, replyToMessageId, blockHash, service, fn } = message || {};
+  const hideServiceAndFn = messageFromProgram.data && messageFromProgram.data.exitCode !== 0;
```
Comment (nikitayutanov) [inline idea/frontend/src/pages/message/message.tsx:38]: Same as above, `isMessageWithError` util is probably better.

**Review by nikitayutanov — APPROVED** [review]
